url: "http://randallandmeghan.wedding"
baseurl: ""

# Site settings
title: Randall & Meghan's Wedding
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Randall Brown
  pic: 1
  position: Groom
  social:
    - title: instagram
      url: https://www.instagram.com/blladnar/

- name: Meghan McDevitt
  pic: 2
  position: Bride
  social:
    - title: instagram
      url: https://www.instagram.com/meghankm14/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

registry:
  - name: REI
    url: https://www.rei.com/GiftRegistryDetails/15285054
    imageUrl: rei.png
    description: Outdoor clothing, gear, and footwear from top brands

  - name: Zola
    url: https://www.zola.com/registry/randallandmeghan
    imageUrl: zola.jpg
    description: The wedding company that'll do anything for love

# Build settings
markdown: kramdown
permalink: pretty
